[theme]
primaryColor = "#00CED1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
runOnSave = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false
